// Create contribution
export const CREATE_CONTRIBUTION_STARTED = 'CREATE_CONTRIBUTION_STARTED';
export const CREATE_CONTRIBUTION_FAILURE = 'CREATE_CONTRIBUTION_FAILURE';
export const CREATE_CONTRIBUTION_SUCCESS = 'CREATE_CONTRIBUTION_SUCCESS';

// Fetch all contributions
export const FETCH_ALL_CONTRIBUTIONS_STARTED =
  'FETCH_ALL_CONTRIBUTIONS_STARTED';
export const FETCH_ALL_CONTRIBUTIONS_FAILURE =
  'FETCH_ALL_CONTRIBUTIONS_FAILURE';
export const FETCH_ALL_CONTRIBUTIONS_SUCCESS =
  'FETCH_ALL_CONTRIBUTIONS_SUCCESS';

// Fetch contributions by barcode
export const FETCH_CONTRIBUTIONS_BY_BARCODE_STARTED =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_STARTED';
export const FETCH_CONTRIBUTIONS_BY_BARCODE_FAILURE =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_FAILURE';
export const FETCH_CONTRIBUTIONS_BY_BARCODE_SUCCESS =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_SUCCESS';

//Fetch contributions by user
export const FETCH_CONTRIBUTIONS_BY_USER_STARTED =
  'FETCH_CONTRIBUTIONS_BY_USER_STARTED';
export const FETCH_CONTRIBUTIONS_BY_USER_FAILURE =
  'FETCH_CONTRIBUTIONS_BY_USER_FAILURE';
export const FETCH_CONTRIBUTIONS_BY_USER_SUCCESS =
  'FETCH_CONTRIBUTIONS_BY_USER_SUCCESS';

// Pagination types
export const FETCH_CONTRIBUTIONS_NEXT_PAGE_STARTED =
  'FETCH_CONTRIBUTIONS_NEXT_PAGE_STARTED';
export const FETCH_CONTRIBUTIONS_NEXT_PAGE_SUCCESS =
  'FETCH_CONTRIBUTIONS_NEXT_PAGE_SUCCESS';
export const FETCH_CONTRIBUTIONS_NEXT_PAGE_FAILURE =
  'FETCH_CONTRIBUTIONS_NEXT_PAGE_FAILURE';

export const FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_STARTED =
  'FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_STARTED';
export const FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_SUCCESS =
  'FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_SUCCESS';
export const FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_FAILURE =
  'FETCH_CONTRIBUTIONS_BY_USER_NEXT_PAGE_FAILURE';

export const FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_STARTED =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_STARTED';
export const FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_SUCCESS =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_SUCCESS';
export const FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_FAILURE =
  'FETCH_CONTRIBUTIONS_BY_BARCODE_NEXT_PAGE_FAILURE';

// Set product attributes
export const SET_BARCODE = 'SET_BARCODE';
export const SET_PRODUCT_IMAGE = 'SET_PRODUCT_IMAGE';

// Image upload attributes
export const IMAGE_UPLOAD_STARTED = 'IMAGE_UPLOAD_STARTED';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_PROGRESS_REPORT = 'IMAGE_UPLOAD_PROGRESS_REPORT';
